services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: logistic_db
      POSTGRES_USER: logistic_user
      POSTGRES_PASSWORD: logistic_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-fallback-key}
      - DEBUG=${DEBUG:-False}
      - DB_NAME=logistic_db
      - DB_USER=logistic_user
      - DB_PASSWORD=logistic_pass
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
